export const dummyData = [
  {
    id: 1,
    name: 'Laptop Pro',
    status: true,
    price: 1200,
    color: '#000000',
    rating: 4.5,
    tags: ['electronics', 'work'],
    lastUpdated: new Date('2024-01-15'),
  },
  {
    id: 2,
    name: 'Smart Phone X',
    status: true,
    price: 800,
    color: '#FF0000',
    rating: 4.0,
    tags: ['electronics', 'mobile'],
    lastUpdated: new Date('2024-01-14'),
  },
  {
    id: 3,
    name: 'Tablet Air',
    status: false,
    price: 500,
    color: '#0000FF',
    rating: 3.5,
    tags: ['electronics', 'mobile'],
    lastUpdated: new Date('2024-01-13'),
  },
  {
    id: 4,
    name: 'Smart Watch',
    status: true,
    price: 300,
    color: '#00FF00',
    rating: 4.8,
    tags: ['electronics', 'wearable'],
    lastUpdated: new Date('2024-01-12'),
  },
  {
    id: 5,
    name: 'Wireless Headphones',
    status: false,
    price: 200,
    color: '#FFFFFF',
    rating: 4.2,
    tags: ['electronics', 'audio'],
    lastUpdated: new Date('2024-01-11'),
  },
  {
    id: 6,
    name: 'Smart Speaker',
    status: true,
    price: 250,
    color: '#C0C0C0',
    rating: 4.3,
    tags: ['electronics', 'audio'],
    lastUpdated: new Date('2024-01-10'),
  },
  {
    id: 7,
    name: 'Gaming Console',
    status: true,
    price: 450,
    color: '#1E90FF',
    rating: 4.7,
    tags: ['electronics', 'gaming'],
    lastUpdated: new Date('2024-01-09'),
  },
  {
    id: 8,
    name: 'Wireless Router',
    status: false,
    price: 150,
    color: '#808080',
    rating: 3.8,
    tags: ['electronics', 'networking'],
    lastUpdated: new Date('2024-01-08'),
  },
  {
    id: 9,
    name: 'Digital Camera',
    status: true,
    price: 600,
    color: '#FFA500',
    rating: 4.4,
    tags: ['electronics', 'photography'],
    lastUpdated: new Date('2024-01-07'),
  },
  {
    id: 10,
    name: 'Bluetooth Earbuds',
    status: true,
    price: 150,
    color: '#FFD700',
    rating: 4.6,
    tags: ['electronics', 'audio'],
    lastUpdated: new Date('2024-01-06'),
  },
  {
    id: 11,
    name: 'Smart TV',
    status: true,
    price: 800,
    color: '#FFFFFF',
    rating: 4.2,
    tags: ['electronics', 'home', 'display'],
    lastUpdated: new Date('2024-01-05'),
  },
  {
    id: 12,
    name: 'Fitness Tracker',
    status: true,
    price: 150,
    color: '#FF5733',
    rating: 4.5,
    tags: ['electronics', 'wearable', 'health'],
    lastUpdated: new Date('2024-01-04'),
  },
  {
    id: 13,
    name: 'Portable Bluetooth Speaker',
    status: false,
    price: 100,
    color: '#33FF99',
    rating: 3.9,
    tags: ['electronics', 'audio', 'portable'],
    lastUpdated: new Date('2024-01-03'),
  },
  {
    id: 14,
    name: 'Wireless Mouse',
    status: true,
    price: 50,
    color: '#AAAAAA',
    rating: 4.0,
    tags: ['electronics', 'peripherals'],
    lastUpdated: new Date('2024-01-02'),
  },
  {
    id: 15,
    name: '4K Action Camera',
    status: true,
    price: 400,
    color: '#FFC0CB',
    rating: 4.6,
    tags: ['electronics', 'photography', 'action'],
    lastUpdated: new Date('2024-01-01'),
  },
  {
    id: 16,
    name: 'Smart Home Hub',
    status: false,
    price: 250,
    color: '#800080',
    rating: 3.7,
    tags: ['electronics', 'home', 'smart'],
    lastUpdated: new Date('2023-12-31'),
  },
  {
    id: 17,
    name: 'Virtual Reality Headset',
    status: true,
    price: 600,
    color: '#00FFFF',
    rating: 4.4,
    tags: ['electronics', 'gaming', 'vr'],
    lastUpdated: new Date('2023-12-30'),
  },
  {
    id: 18,
    name: 'Compact Digital Camera',
    status: true,
    price: 350,
    color: '#FFD700',
    rating: 4.3,
    tags: ['electronics', 'photography', 'compact'],
    lastUpdated: new Date('2023-12-29'),
  },
  {
    id: 19,
    name: 'Smart Thermostat',
    status: true,
    price: 200,
    color: '#008000',
    rating: 4.1,
    tags: ['electronics', 'home', 'smart'],
    lastUpdated: new Date('2023-12-28'),
  },
  {
    id: 20,
    name: 'Wireless Earbuds',
    status: false,
    price: 120,
    color: '#FF69B4',
    rating: 3.8,
    tags: ['electronics', 'audio', 'portable'],
    lastUpdated: new Date('2023-12-27'),
  },
];
